
POST http://localhost:80/sensor/add
Content-Type: application/json
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmI2ZTM2YjdjN2IyZDg3YzE0NTJiMiIsImlhdCI6MTY1MTUxNjQ2MH0.3pFRNobR09lOJXy-Ghm7Ln2tte_xE-EnWqieD-tOCoU

{
  "email" : "tomer@gmail.com",
  "sensor" : "1000000"
}

###

POST http://localhost:80/sensor/removeSensor
Content-Type: application/json
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmI2ZTM2YjdjN2IyZDg3YzE0NTJiMiIsImlhdCI6MTY1MTUxNjQ2MH0.3pFRNobR09lOJXy-Ghm7Ln2tte_xE-EnWqieD-tOCoU

{
  "email" : "tomer@gmail.com",
  "sensor" : "127.0.0.1"
}

###


POST http://localhost:80/sensor/getall
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmI2ZTM2YjdjN2IyZDg3YzE0NTJiMiIsImlhdCI6MTY1MTUxNjQ2MH0.3pFRNobR09lOJXy-Ghm7Ln2tte_xE-EnWqieD-tOCoU

{
    "email" : "tomer@gmail.com"
}

###
POST http://localhost:80/sensor/threshold
Content-Type: application/json
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmI2ZTM2YjdjN2IyZDg3YzE0NTJiMiIsImlhdCI6MTY1MTUxNjQ2MH0.3pFRNobR09lOJXy-Ghm7Ln2tte_xE-EnWqieD-tOCoU

{
  "ip" : "127.0.0.1",
  "threshold": 3

}

###
POST http://localhost:80/sensor/standby
Content-Type: application/json
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmI2ZTM2YjdjN2IyZDg3YzE0NTJiMiIsImlhdCI6MTY1MTUxNjQ2MH0.3pFRNobR09lOJXy-Ghm7Ln2tte_xE-EnWqieD-tOCoU

{
  "ip" : "127.0.0.1",
  "standBy": false
}

###
POST http://localhost:80/sensor/nameSensor
Content-Type: application/json
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmI2ZTM2YjdjN2IyZDg3YzE0NTJiMiIsImlhdCI6MTY1MTUxNjQ2MH0.3pFRNobR09lOJXy-Ghm7Ln2tte_xE-EnWqieD-tOCoU

{
  "id" : "127.0.0.1",
  "name": "My sensor"
}

###

POST https://fcm.googleapis.com/fcm/send
Authorization: key=AAAA4jYnNFw:APA91bGk0Q94BUVgJ7ABRJ3-9rvVpBpHICcSMwGrPCRcujeKR0LhHkzDZRtTEmEZMry-4qaAb9n0IZlcAcKHXDdL8OlZPWlOnuaySPiEuldt9FV1PADJP2IHT8do70k74Uqh5bMQWDW4
Content-Type: application/json

{
  "to": "esF2EDkpSb6jMnXMrr8tRq:APA91bHtvG1D8tFAwpzLQ72mt0aDiNKWmw9eL2ITLCSMuE4trTs4oJoHIOqMEbANhrcYoLehi1J2bq58stHAxNl0Q3ayAortZMfEHFYdPSJ_YYqsF5tbN37aOQlfF4nq0qYqYgXj0TW1",
  "data": {
    "sound": "default",
    "title": "ALERT",
    "body": "ALERT",
    "content_available": true,
    "priority": "high"
  }
}

###                                        # REMOTE SERVER
POST http://193.106.55.120:80/auth/register
Content-Type: application/json

{
    "email" : "ariel@gmail.com",
    "password" : "123456",
    "firebaseToken": "esF2EDkpSb6jMnXMrr8tRq:APA91bHtvG1D8tFAwpzLQ72mt0aDiNKWmw9eL2ITLCSMuE4trTs4oJoHIOqMEbANhrcYoLehi1J2bq58stHAxNl0Q3ayAortZMfEHFYdPSJ_YYqsF5tbN37aOQlfF4nq0qYqYgXj0TW1"
}

###                                   # LOCAL SERVER
POST http://127.0.0.1:80/auth/register
Content-Type: application/json

{
  "email" : "tomer@gmail.com",
  "password" : "123456",
  "firebaseToken": "esF2EDkpSb6jMnXMrr8tRq:APA91bHtvG1D8tFAwpzLQ72mt0aDiNKWmw9eL2ITLCSMuE4trTs4oJoHIOqMEbANhrcYoLehi1J2bq58stHAxNl0Q3ayAortZMfEHFYdPSJ_YYqsF5tbN37aOQlfF4nq0qYqYgXj0TW1"
}

###


POST http://localhost:80/auth/login
Content-Type: application/json

{
    "email" : "tomer@gmail.com",
    "password" : "123456",
    "firebaseToken": "esF2EDkpSb6jMnXMrr8tRq:APA91bHtvG1D8tFAwpzLQ72mt0aDiNKWmw9eL2ITLCSMuE4trTs4oJoHIOqMEbANhrcYoLehi1J2bq58stHAxNl0Q3ayAortZMfEHFYdPSJ_YYqsF5tbN37aOQlfF4nq0qYqYgXj0TW1"
}

###
POST http://localhost:80/auth/logout
Content-Type: application/json

{
  "email" : "tomer@gmail.com"
}
