
###


GET http://localhost:28017/



###


GET http://localhost:28017/sensor
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGQ0YmFhZGNmZjM0ODMyZmZmMzBhNiIsImlhdCI6MTY0NTA0MDUxNSwiZXhwIjoxNjQ1MDQwNTQ1fQ.MxJ76Q6D3tiFP7i6pe1zEogk_cnvsRYcxXBHwsmA_rQ
###


GET http://localhost:28017/sensor/620d3347abfb42d96325fcc5

###


POST http://localhost:28017/sensor
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGQ0YmFhZGNmZjM0ODMyZmZmMzBhNiIsImlhdCI6MTY0NTA0MDcxMiwiZXhwIjoxNjQ1MDQwNzQyfQ.J5n0F-8aTZrlqtjcRfcD4SXTzDWA1iaIsIxwplB5964
Content-Type: application/json

{
    "message" : "this is my authorized new post",
    "sender" : "Eliav"
}

###


POST http://localhost:28017/auth/register
Content-Type: application/json

{
    "email" : "ariel@gmail.com",
    "password" : "123456",
    "firebaseToken": "batomeromerrr"
}

###


POST http://localhost:28017/auth/login
Content-Type: application/json

{
    "email" : "ariel@gmail.com",
    "password" : "123456",
    "firebaseToken": "dayakshtra"
}

###


POST http://localhost:28017/auth/logout
Content-Type: application/json

{
    "message" : "this is my new post",
    "sender" : "Eliav"
}